version: '3.8'
volumes:
  node_modules:
services:
  js_based_project:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: deps
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
